ci: fix pipeline name to unpause on repipe
to fix:
./ci/repipe
Updating pipeline @ ciblink
no changes to apply
error: Unexpected Response
Status: 409 Conflict
Body: action not allowed for an archived pipeline